# GitHub Actions workflow para build e deploy do portfólio
name: Build and Deploy Portfolio

# Trigger do workflow
on:
  # Executa quando há push na branch main
  push:
    branches: [main]

  # Permite execução manual do workflow
  workflow_dispatch:

# Define as permissões necessárias para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Garante que apenas um deploy rode por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Instalação das dependências
      - name: Install Dependencies
        run: npm ci

      # Execução do linting
      - name: Run Linting
        run: npm run lint

      # Build do projeto
      - name: Build Project
        run: npm run build

      # Setup do GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload dos artefatos do build
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  # Job de deploy
  deploy:
    # Depende do job de build
    needs: build

    # Executa no ambiente de GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
